repos:
  - repo: local
    hooks:
      - id: ruff-fix
        name: Ruff Fixes
        entry: ruff check --fix --unsafe-fixes
        language: system
        types: [python]
      - id: mypy-check
        name: Mypy Type Check
        entry: mypy --explicit-package-bases .
        language: system
        types: [python]
      - id: pytest-check
        name: Run Tests
        entry: pytest tests/
        language: system
        types: [python]
