version: '3.8'
name: spark-cluster
services:
  spark-master:
    user: root
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark-master
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=root
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/spark/work-dir/spark-events
      - PYTHONPATH=/src
    ports:
      - '8080:8080'
      - '7077:7077'
      - "18080:18080"  # Spark History Server Web UI
    volumes:
      - ./src:/src
      - spark-events:/opt/spark/work-dir/spark-events
      - ./data:/opt/bitnami/spark/data
    networks:
      - spark-net
    command: ["/bin/bash", "-c", "spark-class org.apache.spark.deploy.master.Master & spark-class org.apache.spark.deploy.history.HistoryServer"]

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=root
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
    volumes:
      - ./src:/src
      - ./data:/opt/bitnami/spark/data
    depends_on:
      - spark-master
    ports:
      - "8081"
    networks:
      - spark-net

volumes:
  spark-events:

networks:
  spark-net:
    driver: bridge